INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Afghanistan', 'AF', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ägypten', 'EG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Albanien', 'AL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Algerien', 'DZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Andorra', 'AD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Angola', 'AO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Antigua und Barbuda', 'AG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Äquatorialguinea', 'GQ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Argentinien', 'AR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Armenien', 'AM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Aserbaidschan', 'AZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Äthiopien', 'ET', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Australien', 'AU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bahamas', 'BS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bahrain', 'BH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bangladesch', 'BD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Barbados', 'BB', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Belarus', 'BY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Belgien', 'BE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Belize', 'BZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Benin', 'BJ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bhutan', 'BT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bolivien', 'BO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bosnien und Herzegowina', 'BA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Botswana', 'BW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Brasilien', 'BR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Brunei', 'BN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Bulgarien', 'BG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Burkina Faso', 'BF', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Burundi', 'BI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Chile', 'CL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Republik China (Taiwan)', 'TW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Volksrepublik China', 'CN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Cookinseln', 'CK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Costa Rica', 'CR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Dänemark', 'DK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Deutschland', 'DE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Dominica', 'DM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Dominikanische Republik', 'DO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Dschibuti', 'DJ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ecuador', 'EC', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('El Salvador', 'SV', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Elfenbeinküste', 'CI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Eritrea', 'ER', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Estland', 'EE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Eswatini', 'SZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Fidschi', 'FJ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Frankreich', 'FR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Gabun', 'GA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Gambia', 'GM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Georgien', 'GE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ghana', 'GH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Grenada', 'GD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Griechenland', 'GR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Guatemala', 'GT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Guinea', 'GN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Guinea-Bissau', 'GW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Guyana', 'GY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Haiti', 'HT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Honduras', 'HN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Indien', 'IN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Indonesien', 'ID', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Irak', 'IQ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Iran', 'IR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Irland', 'IE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Island', 'IS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Israel', 'IL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Italien', 'IT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Jamaika', 'JM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Japan', 'JP', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Jemen', 'YE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Jordanien', 'JO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kambodscha', 'KH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kamerun', 'CM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kanada', 'CA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kap Verde', 'CV', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kasachstan', 'KZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Katar', 'QA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kenia', 'KE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kirgisistan', 'KG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kiribati', 'KI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kolumbien', 'CO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Komoren', 'KM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Demokratische Republik Kongo', 'CD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Republik Kongo', 'CG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nordkorea', 'KP', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Südkorea', 'KR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kosovo', 'XK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kroatien', 'HR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kuba', 'CU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Kuwait', 'KW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Laos', 'LA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Lesotho', 'LS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Lettland', 'LV', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Libanon', 'LB', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Liberia', 'LR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Libyen', 'LY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Liechtenstein', 'LI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Litauen', 'LT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Luxemburg', 'LU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Madagaskar', 'MG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Malawi', 'MW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Malaysia', 'MY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Malediven', 'MV', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mali', 'ML', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Malta', 'MT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Marokko', 'MA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Marshallinseln', 'MH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mauretanien', 'MR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mauritius', 'MU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mexiko', 'MX', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Föderierte Staaten von Mikronesien', 'FM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Republik Moldau', 'MD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Monaco', 'MC', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mongolei', 'MN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Montenegro', 'ME', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Mosambik', 'MZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Myanmar', 'MM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Namibia', 'NA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nauru', 'NR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nepal', 'NP', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Neuseeland', 'NZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nicaragua', 'NI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Niederlande', 'NL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Niger', 'NE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nigeria', 'NG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Niue', 'NU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Nordmazedonien', 'MK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Norwegen', 'NO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Oman', 'OM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Österreich', 'AT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Pakistan', 'PK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Staat Palästina', 'PS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Palau', 'PW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Panama', 'PA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Papua-Neuguinea', 'PG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Paraguay', 'PY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Peru', 'PE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Philippinen', 'PH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Polen', 'PL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Portugal', 'PT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ruanda', 'RW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Rumänien', 'RO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Russland', 'RU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Salomonen', 'SB', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Sambia', 'ZM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Samoa', 'WS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('San Marino', 'SM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('São Tomé und Príncipe', 'ST', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Saudi-Arabien', 'SA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Schweden', 'SE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Schweiz', 'CH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Senegal', 'SN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Serbien', 'RS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Seychellen', 'SC', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Sierra Leone', 'SL', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Simbabwe', 'ZW', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Singapur', 'SG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Slowakei', 'SK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Slowenien', 'SI', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Somalia', 'SO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Spanien', 'ES', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Sri Lanka', 'LK', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('St. Kitts und Nevis', 'KN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('St. Lucia', 'LC', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('St. Vincent und die Grenadinen', 'VC', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Südafrika', 'ZA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Sudan', 'SD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Südsudan', 'SS', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Suriname', 'SR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Syrien', 'SY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tadschikistan', 'TJ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tansania', 'TZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Thailand', 'TH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Togo', 'TG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tonga', 'TO', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Trinidad und Tobago', 'TT', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tschad', 'TD', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tschechien', 'CZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tunesien', 'TN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Türkei', 'TR', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Turkmenistan', 'TM', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Tuvalu', 'TV', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Uganda', 'UG', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ukraine', 'UA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Ungarn', 'HU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Uruguay', 'UY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Usbekistan', 'UZ', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Vanuatu', 'VU', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Vatikanstadt', 'VA', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Venezuela', 'VE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Vereinigte Arabische Emirate', 'AE', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Vereinigte Staaten', 'US', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Vietnam', 'VN', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Demokratische Arabische Republik Sahara', 'EH', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Zentralafrikanische Republik', 'CF', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) VALUES ('Republik Zypern', 'CY', NULL);
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Baden-Württemberg', 'BW', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Bayern', 'BY', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Berlin', 'BE', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Brandenburg', 'BB', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Bremen', 'HB', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Hamburg', 'HH', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Hessen', 'HE', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Mecklenburg-Vorpommern', 'MV', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Niedersachsen', 'NI', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Nordrhein-Westfalen', 'NW', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Rheinland-Pfalz', 'RP', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Saarland', 'SL', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Sachsen', 'SN', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Sachsen-Anhalt', 'ST', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Schleswig-Holstein', 'SH', `id` FROM region WHERE `name` = 'Deutschland';
INSERT INTO region (`name`, `short_name`, `parent_id`) SELECT 'Thüringen', 'TH', `id` FROM region WHERE `name` = 'Deutschland';